tmp_dir: ./tmp
config_dir: ./configs
# BEGIN ANSIBLE MANAGED BLOCK
global: 
  bgp_asn: 65400
  core_subnet: 10.1.1.0/24
  dns:
  - 172.20.1.1
  - 172.20.1.15
  loopback_subnet: 10.100.1.0/24
  mgmt_gw: 172.20.1.1
  mgmt_prefixes:
  - 192.168.0.0/24
  - 10.8.0.0/24
  mtu: 1500
  netconf_port: 830
  ospf_area: 0
  ospf_pid: 1
  p2p_prefix: 31
  root_pwd: $1$ciI4raxU$XfCVzABJKdALim0aWVMql0
  setup: isp
  users:
  -   hash: $1$mR940Z9C$ipX9sLKTRDeljQXvWFfJm1
      passwd: 14161C180506262E757A60
      role: super-user
      username: ansible

p2p_ip:
  EDG-001.dc1:
    - {port: ge-0/0/0, ip: 10.1.1.1 , peer: SPN-001.dc1, pport: ge-0/0/0, peer_ip: 10.1.1.0}
    - {port: ge-0/0/1, ip: 10.1.1.5 , peer: SPN-002.dc1, pport: ge-0/0/0, peer_ip: 10.1.1.4}
  EDG-002.dc1:
    - {port: ge-0/0/0, ip: 10.1.1.3 , peer: SPN-001.dc1, pport: ge-0/0/1, peer_ip: 10.1.1.2}
    - {port: ge-0/0/1, ip: 10.1.1.7 , peer: SPN-002.dc1, pport: ge-0/0/1, peer_ip: 10.1.1.6}
  SPN-001.dc1:
    - {port: ge-0/0/0, ip: 10.1.1.0 , peer: EDG-001.dc1, pport: ge-0/0/0, peer_ip: 10.1.1.1}
    - {port: ge-0/0/1, ip: 10.1.1.2 , peer: EDG-002.dc1, pport: ge-0/0/0, peer_ip: 10.1.1.3}
  SPN-002.dc1:
    - {port: ge-0/0/0, ip: 10.1.1.4 , peer: EDG-001.dc1, pport: ge-0/0/1, peer_ip: 10.1.1.5}
    - {port: ge-0/0/1, ip: 10.1.1.6 , peer: EDG-002.dc1, pport: ge-0/0/1, peer_ip: 10.1.1.7}

lo_ip:
  EDG-001.dc1: 10.100.1.103/32
  EDG-002.dc1: 10.100.1.104/32
  SPN-001.dc1: 10.100.1.101/32
  SPN-002.dc1: 10.100.1.102/32


mgmt_net:
  EDG-001.dc1:
      ip: 172.20.1.4/28
      port: em0
  EDG-002.dc1:
      ip: 172.20.1.5/28
      port: em0
  SPN-001.dc1:
      ip: 172.20.1.2/28
      port: em0
  SPN-002.dc1:
      ip: 172.20.1.3/28
      port: em0


bgp_topo:
  af:
  - inet
  - inet-vpn
  peers:
      EDG-001.dc1:
      - SPN-001.dc1
      - SPN-002.dc1
      - EDG-002.dc1
      EDG-002.dc1:
      - EDG-001.dc1
      SPN-001.dc1:
      - EDG-001.dc1
      SPN-002.dc1:
      - EDG-001.dc1
  rr: EDG-001.dc1
# END ANSIBLE MANAGED BLOCK