- name: Delete NetBox Devices
  netbox_device:
    data:
      name: "{{ inventory_hostname }}"
      device_role: "{{ device_role }}"
      device_type: "{{ device_model }}"
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    state: "{{ netbox_state }}"
  tags: netbox_devices

- name: Delete NetBox Device Types
  include_tasks: remove_device_types.yml
  run_once: yes
  tags: device_types

- name: Delete NetBox Device Roles
  include_tasks: remove_device_roles.yml
  run_once: yes
  tags: device_roles

- name: Delete NetBox Device Vendors
  include_tasks: remove_device_vendors.yml
  run_once: yes
  tags: device_vendors

- name: Delete IP Prefixes
  netbox_prefix:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    data:
      prefix: "{{ item.prefix }}"
      site: "{{ item.site | default(omit) }}"
      status: Active
    state: "{{ netbox_state }}"
    validate_certs: no
  loop: "{{ subnets }}"
  loop_control:
    label: "{{ item.prefix }}"
  run_once: yes        
  tags: netbox_prefix

- name: Delete NetBox Sites
  netbox_site:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    data:
      name: "{{ item.name | lower }}"
      description: "{{ item.description | default(omit) }}"
      physical_address: "{{ item.location | default(omit) }}"
    state: "{{ netbox_state }}"
  loop: "{{ sites }}" 
  when: sites is defined
  run_once: yes
  tags: netbox_sites