- name: NetBox Device  // Get Existing Device Types
  uri:
    url: "{{ netbox_url }}/api/dcim/device-types/" 
    method: GET
    headers:
      Authorization: "Token {{ netbox_token }}"
      Accept: 'application/json'
    return_content: yes
    body_format: json
    status_code: [200, 201]
  register: netbox_device_types
  tags: device_types
# - debug: var=netbox_device_types
#   tags: device_types

- name: NetBox Device  // DELETE Existing Device Types
  uri:
    url: "{{ netbox_url }}/api/dcim/device-types/{{ device.id }}/" 
    method: DELETE
    headers:
      Authorization: "Token {{ netbox_token }}"
      Accept: 'application/json'
    # return_content: yes
    # body_format: json
    status_code: [200, 201,204]
  loop: "{{ netbox_device_types.json.results }}"
  loop_control:
    loop_var: device
  when: netbox_device_types.json.count != 0 and netbox_state == 'absent'
  tags: device_types

