---
- name: Create NetBox Sites
  netbox_site:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    data:
      name: "{{ item.name | lower }}"
      description: "{{ item.description | default(omit) }}"
      physical_address: "{{ item.location | default(omit) }}"
    state: "{{ netbox_state }}"
  loop: "{{ sites }}" 
  when: sites is defined
  run_once: yes
  tags: netbox_sites

- name: Create NetBox Device Vendors
  include_tasks: create_device_vendors.yml
  loop: "{{ devices | map(attribute='vendor') | list | unique}}"
  loop_control:
    loop_var: device
  run_once: yes
  tags: 
    - device_vendors

- name: Create NetBox Device Types
  include_tasks: create_device_types.yml
  loop: "{{ devices }}"
  loop_control:
    loop_var: device
  run_once: yes
  tags: 
    - device_types

- name: Create NetBox Device Roles
  include_tasks: create_device_roles.yml
  loop: "{{ devices }}"
  loop_control:
    loop_var: device
  run_once: yes
  tags: 
    - device_roles

- name: Create NetBox Device 
  include_tasks: create_device.yml
  tags: netbox_devices

- name: Create NetBox Device Interfaces
  include_tasks: create_device_intf.yml
  tags: netbox_intfs

- name: Create NetBox Device Interfaces IP Address
  include_tasks: create_device_intf_ip.yml
  tags: netbox_ip

- name: Set Primary IP for Device
  include_tasks: create_primary_ip.yml
  tags: netbox_mgmt_ip

# - debug: var=discovered_interpreter_python
#   tags: netbox_prefix

- name: Create IP Prefixes
  netbox_prefix:
    netbox_token: "{{ netbox_token }}"
    netbox_url: "{{ netbox_url }}"
    data:
      prefix: "{{ item.prefix }}"
      site: "{{ item.site | default(omit) }}"
      status: Active
    state: "{{ netbox_state }}"
    validate_certs: no
  loop: "{{ subnets }}"
  loop_control:
    label: "{{ item.prefix }}"
  run_once: yes        
  tags: netbox_prefix



